In [1]:
import numpy as np

In [6]:
a = np.array([[1, 0], [0, 1]])
a

array([[1, 0],
       [0, 1]])

In [8]:
b = np.array([[1, 2], [3, 1]])
b

array([[1, 2],
       [3, 1]])

In [11]:
np.matmul(a, b)

array([[1, 2],
       [3, 1]])

In [12]:
a*b

array([[1, 0],
       [0, 1]])